name: Primeira-Pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Primeira ação"
        run: echo "Wello World"
      - name: "Segunda ação"
        run: |
          echo "Segunda ação"
          echo "Terceira ação"
  segundo-job:
    name: "Usando Action do Node"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificando a versão default"
        run: node --version
      - name: "Ambiente de Node Atualizado" 
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "22.13.0"
      - name: "Verificando a nova versão"
        run: node --version
          
      
  
