name: Primeira-Pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Primeira ação"
        run: echo "Wello World"
      - name: "Segunda ação"
        run: |
          echo "Segunda ação"
          echo "Terceira ação"
    
  
